services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - backend
  
  backend:
    build: ./backend
    expose:
      - "3000"
